<a href="https://colab.research.google.com/github/Anshuman262005/6thSem-ML-Lab/blob/main/1bm23cs043_lab4_decision_tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.metrics import accuracy_score, confusion_matrix, mean_absolute_error, mean_squared_error

# --- 1. Iris Dataset Classification ---
print("--- Task 1: Iris Dataset Classification ---")
try:
    iris_df = pd.read_csv('iris.csv')
    X_iris = iris_df.drop('species', axis=1)
    y_iris = iris_df['species']
    X_train_i, X_test_i, y_train_i, y_test_i = train_test_split(X_iris, y_iris, test_size=0.20, random_state=42)

    clf_iris = DecisionTreeClassifier(random_state=42)
    clf_iris.fit(X_train_i, y_train_i)
    y_pred_i = clf_iris.predict(X_test_i)

    print(f"Accuracy Score: {accuracy_score(y_test_i, y_pred_i):.2f}")
    print("Confusion Matrix:\n", confusion_matrix(y_test_i, y_pred_i))
except FileNotFoundError:
    print("iris.csv not found.")

# --- 2. Drug Dataset Classification ---
print("\n--- Task 2: Drug Dataset Classification ---")
try:
    drug_df = pd.read_csv('drug.csv')
    # One-hot encode categorical features
    X_drug = pd.get_dummies(drug_df.drop('Drug', axis=1))
    y_drug = drug_df['Drug']
    X_train_d, X_test_d, y_train_d, y_test_d = train_test_split(X_drug, y_drug, test_size=0.20, random_state=42)

    clf_drug = DecisionTreeClassifier(random_state=42)
    clf_drug.fit(X_train_d, y_train_d)
    y_pred_d = clf_drug.predict(X_test_d)

    print(f"Accuracy Score: {accuracy_score(y_test_d, y_pred_d):.2f}")
    print("Confusion Matrix:\n", confusion_matrix(y_test_d, y_pred_d))
except FileNotFoundError:
    print("drug.csv not found.")

# --- 3. Petrol Consumption Regression ---
print("\n--- Task 3: Petrol Consumption Regression ---")
try:
    petrol_df = pd.read_csv('petrol_consumption.csv')
    X_petrol = petrol_df.drop('Petrol_Consumption', axis=1)
    y_petrol = petrol_df['Petrol_Consumption']
    X_train_p, X_test_p, y_train_p, y_test_p = train_test_split(X_petrol, y_petrol, test_size=0.20, random_state=42)

    reg_petrol = DecisionTreeRegressor(random_state=42)
    reg_petrol.fit(X_train_p, y_train_p)
    y_pred_p = reg_petrol.predict(X_test_p)

    mae = mean_absolute_error(y_test_p, y_pred_p)
    mse = mean_squared_error(y_test_p, y_pred_p)
    rmse = np.sqrt(mse)

    print(f"Mean Absolute Error: {mae:.2f}")
    print(f"Mean Squared Error: {mse:.2f}")
    print(f"Root Mean Squared Error: {rmse:.2f}")
except FileNotFoundError:
    print("petrol_consumption.csv not found.")

--- Task 1: Iris Dataset Classification ---
Accuracy Score: 1.00
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

--- Task 2: Drug Dataset Classification ---
Accuracy Score: 1.00
Confusion Matrix:
 [[ 6  0  0  0  0]
 [ 0  3  0  0  0]
 [ 0  0  5  0  0]
 [ 0  0  0 11  0]
 [ 0  0  0  0 15]]

--- Task 3: Petrol Consumption Regression ---
Mean Absolute Error: 94.30
Mean Squared Error: 17347.70
Root Mean Squared Error: 131.71
